### ISSUE TITLE
Error: spawn node_modules\typescript\bin\tsc ENOENT

### ISSUE THREAD

**Issue by leonardochaia** [Offirmo/node-typescript-compiler#4]
Hi, I'm attempting to use this and I get the following error:

```
PS C:\test-tsc> node test.js
[node-typescript-compiler] spawning C:\test-tsc\node_modules\typescript\bin\tsc --help

{ Error: Spawn : got err event : Error: spawn C:\test-tsc\node_modules\typescript\bin\tsc ENOENT
    at fail (C:\test-tsc\node_modules\node-typescript-compiler\index.js:56:17)
    at ChildProcess.spawn_instance.on.err (C:\test-tsc\node_modules\node-typescript-compiler\index.js:65:5)
    at emitOne (events.js:125:13)
    at ChildProcess.emit (events.js:221:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) stdout: '', stderr: '' }
(node:10532) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Spawn : got err event : Error: spawn C:\test-tsc\node_modules\typescript\bin\tsc ENOENT
(node:10532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js
process with a non-zero exit code.
{ Error: Spawn : got event close with error code "-4058" & signal "null"
    at fail (C:\test-tsc\node_modules\node-typescript-compiler\index.js:56:17)
    at ChildProcess.spawn_instance.on (C:\test-tsc\node_modules\node-typescript-compiler\index.js:80:6)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at Pipe._handle.close [as _onclose] (net.js:558:12) stdout: '', stderr: '' }
```

package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "node-typescript-compiler": "^1.1.1",
    "typescript": "^3.0.1"
  }
}
```

test.js
```javascript
const tsc = require('node-typescript-compiler')
 
return tsc.compile({
    'help': true
})
```

```powershell
node.test.js
```

**Comment by Offirmo** [comment]
It seems node-typescript-compiler has a hard time finding the "tsc" executable. Did you install "typescript" as a dependency? If yes (as it seems above) did you `npm install`?

It's also possible that typescript 3 has changed the path of `tsc`. I have yet to migrate to typescript 3 myself...

**Comment by leonardochaia** [comment]
Hi @Offirmo, I did run `npm install`.

I have just tried with Typescript 2.9.2 and I get the same error. It must be something with my environment.

I have also tried creating a package.json script with `node test.js` and I get the same error.

Any suggestions? 

Thank you.

**Comment by Offirmo** [comment]
Sorry I'm going on holiday 2 weeks.

I checked TS 3 and the tsc executable is at the correct place...

**Comment by leonardochaia** [comment]
No problem, I'll see what I can do.

Have fun 👍

**Comment by ennovum** [comment]
@leonardochaia @Offirmo any luck with this? I'm facing the same.

I did some research and I think this line is the faulty one:
```
const spawn_instance = spawn(spawn_executable, spawn_params, spawn_options)
```

`spawn_executable` is found alright, but it's a JS file. I wouldn't expect mswin to be able to just run it as Node.JS is not a first class citizen in that OS. Any suggestions?

If I tweak the line as follows, it is able to run, but there are other `tsconfig` related issues:
```
const spawn_instance = spawn('node ' + spawn_executable, spawn_params, spawn_options)
```

**Comment by leonardochaia** [comment]
@ennovum I don't remember correctly, but I think I ended up not using this at all, not sure why. I do remember I couldn't make it work.
I'm sorry I can't be of further assistance.

**Comment by Offirmo** [comment]
Hi mates,
1. this tool moved to another repo: https://github.com/Offirmo/offirmo-monorepo/tree/master/4-tools/node-typescript-compiler
1. I just pushed v2.1.1 with better error reporting. Also you can use "verbose: true" which was previously undocumented. Check the doc.

I'll close this issue, please reopen in the other repo.
